---
ai: Demo
ai_options:
    Behavioral:
        avoid_branch: mines

# interface: Local
interface: Telnet
interface_options:
    Telnet:
        account: doytaeb

display: Curses
display_options:
    Curses:
        color_method: debug

character:
    role: Valkyrie
    race: Dwarf
    gender: Female
    align: Law

logger:
    log_rotate:
        dir: logs
        compress: 1

# debug:
    # irc:
        # server: irc.freenode.net
        # port:   6667
        # channel: "#interhack"
        # name: doytaeb

other_config:
    - pass_config.yml
